### ISSUE TITLE
`extensions` not respected if `main` package file entry is found

### ISSUE THREAD

**Issue by huerlisi** [browserify/resolve#102]
There's is the `extensions` option to specify what extensions the file we want to resolve needs to have. This is not respected when the target is also the name of a module and that module has a `main` field in the `package.json`.

In my opinion the file specified in `main` should only be used if it satisfies the `extensions` filter.

**Comment by ljharb** [comment]
What does node itself do in this situation?

**Comment by jasonk** [comment]
Node does the same thing that resolve does, it uses whatever `main` said to use.  `extensions` isn't a filter, it's a search list used when trying to locate files for an import that might not have an extension included.

**Comment by ljharb** [comment]
@jasonk right, but if you put "index" in "main", node will search through `require.extensions` to match it, and will also look for a "main" in `index/` if that's a directory.
