### ISSUE TITLE
Add http2 to list of core modules

### ISSUE THREAD

**Issue by vinsonchuong** [browserify/resolve#139]
Hello! I'm starting to experiment with the new `http2` module. I'm wondering if it can be added to `isCore`

For more context on my particular use, I'm using a linter plugin `eslint-plugin-import` that uses this package. It fails to recognize the existence of the `http2` module.

**Comment by ljharb** [comment]
What node version ships `http2` as a core module unflagged?

**Comment by vinsonchuong** [comment]
It's not shipped unflagged in any version of Node. Is it an assumption that `isCore` return only unflagged modules? If so, let's close this.

**Comment by ljharb** [comment]
I think it might be reasonable to feature-detect when `http2` is available as a core module, and return it in that case - then some extra logic would need to go in https://github.com/browserify/resolve/blob/master/lib/core.js.

However, currently, the list only includes unflagged modules, yes.

**Comment by ljharb** [comment]
node v8.8+ has `http2` unflagged.
