### ISSUE TITLE
How to refer to files/directories inside environment variables

### ISSUE THREAD

**Issue by Nilesh0101** [browserify/resolve#140]
I'm using PKG tool for packaging nodejs application. Pkg uses Resolve module internally.
I have set environment variables inside package.json. Inside require statements I'm accessing files/directories assuming environment variables are set.
Problem is that Resolve could not resolve the paths inside require statements.
Please refer below urls for more information
https://github.com/zeit/pkg/issues/230 and https://github.com/zeit/pkg/issues/233

Thanks in Advance.

**Comment by ljharb** [comment]
`require` does not care what's in `$PATH`; that's not how node works.

Separately, there's no "env" key in package.json that anything looks at, so that doesn't actually cause env vars to be set.

Your app should have relative paths, and not try to do bare requires from "not node_modules".
