### ISSUE TITLE
Getting very different results when using SYNC vs ASYNC

### ISSUE THREAD

**Issue by jasonmacdonald** [browserify/resolve#142]
I'm trying to follow a very long trail from Jest -> browser-resolve -> resolve where the package.json `browser` field is not being applied to transform a files reference.

Jest calls browser-resolve using it's `sync` method, which in turn calls resolve using its `sync` method. Under this the file returned is not the correct file.

However, if I run an additional request on the side to async, and give it a callback, that request returns the proper file mapped via the browser flag. 

Is there any reason that async would be returning very different results to sync? I suspect it may have something to do with the fact that async has a `pathFilter` option, where sync does not. And I'm trying to understand if somewhere along the path of files that that method not being called is causing issues.

Frankly, this is a real confusing mess to try and follow, especially when having to do it through Jest which loves to swallow console.logs and is very difficult to debug through.

**Comment by jasonmacdonald** [comment]
Even looking at the files, the `loadAsFileSync` function is only 11 lines of code, yet the `loadAsFile` in Async is over 40 lines, including the loading of a package.json for the directory the source file is in. This causes very different results. Why are these two so different if the only intentional difference is wether or not it is a synchronous or asynchronous response?

**Comment by ljharb** [comment]
Perhaps @substack can comment.

Regardless, I think it would make sense to add `pathFilter` to the sync method (in general, to have the options be symmetric), and it does seem suspect to have them return different results.

If you can reduce it to a reproducible test case (outside of jest) that would be most helpful.

**Comment by lbogdan** [comment]
Hey guys!

Just wanted to let you know I also hit this issue hard while chasing a bug in [CodeSandbox](https://codesandbox.io). Indeed, the sync version doesn't honor the `browser` field from `package.json` (actually it doesn't even load `package.json` in the first place).

I managed to fix it by getting `loadAsFileSync()` pretty much on par with `loadAsFile()`. I'll get back to you tomorrow, as it's 3AM here. Cheers!

**Comment by lbogdan** [comment]
As promised, here's a reproduction of this bug: http://pr337.cs.lbogdan.tk/s/5233441z5l . If you look in the console, you'll see
```
sync resolving readable-stream/writable.js...
isFileSync /node_modules/readable-stream/writable.js
resolve.sync() returned /node_modules/readable-stream/writable.js
async resolving readable-stream/writable.js...
isFile /node_modules/readable-stream/package.json
readFile /node_modules/readable-stream/package.json
isFile /node_modules/readable-stream/writable-browser.js
resolve() returned /node_modules/readable-stream/writable-browser.js
```

**Comment by lbogdan** [comment]
And this is my naive try at fixing this: https://github.com/lbogdan/resolve/commit/feb39f28c32321710796d06855a6f6a9ae8483a1 - I pretty much copied what `loadAsFile()` does in a sync way.

**Comment by lbogdan** [comment]
We deployed these changes ^^ on [CodeSandbox](https://codesandbox.io/) today, and until now everything seems to be fine. I'll keep you posted if there are further developments.

**Comment by lbogdan** [comment]
Hello again, and a happy new year! :smile: 

@ljharb , @substack Any news about this? Was it fixed meanwhile?
Just wanted to let you know that we didn't have any more issues on CodeSandbox using the above fix, should I go ahead and make a PR?

**Comment by ljharb** [comment]
@lbogdan a PR would be great, and we can discuss from there.
