### ISSUE TITLE
Node's require.resolve options

### ISSUE THREAD

**Issue by reggi** [browserify/resolve#150]
I see there's a lot of discussion about what the _defaults_ should be for this module. It seems like it's too late for that.  This module is already in use. However I'm using this in a project and expected `.json` to work as well as `package.json` main, and it's not. I would appreciate if someone could share what `options` that should be passed to mimic the node's default, perhaps we can add another function to this module in the future or just add it to the docs to help mitigate confusion.

How do I get it to check for `package.json` main?

Starting the config here:

```json
{
  "extensions": [ ".js", ".json", ".node"]
}
```

**Comment by ljharb** [comment]
That indeed should do it, since those are the default extensions; you can also do `"extensions": require.extentions`

**Comment by reggi** [comment]
Ah, ok the issue i'm having is related to Promises.
