### ISSUE TITLE
Confusing error message when "basedir" is not a directory

### ISSUE THREAD

**Issue by gaearon** [browserify/resolve#154]
I mistakingly passed a filename as `basedir` option.
I found the error message quite confusing:

```js
TypeError: Cannot read property 'isFile' of undefined
    at isFile (/Users/gaearon/p/test113/node_modules/resolve/lib/sync.js:12:20)
    at loadAsFileSync (/Users/gaearon/p/test113/node_modules/resolve/lib/sync.js:36:13)
    at loadNodeModulesSync (/Users/gaearon/p/test113/node_modules/resolve/lib/sync.js:75:21)
```

This is because there is an early exit for "file not found" errors, but for any other errors we fall through to where `stat` doesn't exist.

Just filing this for future readers.

**Comment by ljharb** [comment]
Thanks; I've added some tests to ensure that the behavior doesn't change.

In the next major (because changing error messages has been a breaking change for this lib in the past), I'll improve the error message here so that it's explicit about what you did wrong :-)
