### ISSUE TITLE
doesn't support `$HOME/.node_modules` or `$HOME/.node_libraries`

### ISSUE THREAD

**Issue by mk-pmb** [browserify/resolve#163]
Hi, thanks for this module!
It seems  to have trouble finding my packages, though:

```bash
$ readlink -m ~/.node_modules
/mnt/…/nodejs/modules
$ nodejs -e 'console.log(require.resolve("lodash")); require("resolve")("lodash", console.log);'
/mnt/…/nodejs/modules/lodash/lodash.js
{ Error: Cannot find module 'lodash' from '.'
    at /mnt/…/nodejs/modules/resolve/lib/async.js:50:31
    at processDirs (/mnt/…/nodejs/modules/resolve/lib/async.js:184:39)
    at ondir (/mnt/…/nodejs/modules/resolve/lib/async.js:199:13)
    at load (/mnt/…/nodejs/modules/resolve/lib/async.js:82:43)
    at onex (/mnt/…/nodejs/modules/resolve/lib/async.js:107:17)
    at /mnt/…/nodejs/modules/resolve/lib/async.js:12:69
    at FSReqWrap.oncomplete (fs.js:152:21) code: 'MODULE_NOT_FOUND' }
```

So `require.resolve` was able to find it, but `resolve` wasn't. However, it works when I create a symlink `/mnt/…/nodejs/node_modules` to `modules`.

Update: Work-around: It also works when I pass option `{ paths: [process.env.HOME + "/.node_modules"] }`
Update 2: However, in that case I have to then explicitly resolve the returned path in order to get the exact same result.

**Comment by ljharb** [comment]
I think you'll need to set the `preserveSymlinks` option to `true`.

**Comment by mk-pmb** [comment]
Nope, doesn't seem to help:

```bash
$ nodejs -e 'console.log(require.resolve("lodash")); require("resolve")("lodash", { preserveSymlinks: true }, console.log);' 
/mnt/basecamp/app-res/nodejs/modules/lodash/lodash.js
{ Error: Cannot find module 'lodash' from '.'
[…]
```

**Comment by mk-pmb** [comment]
To clarify, with "explicitly resolve the returned path" I meant I have to `fs.realpath()` it myself.

**Comment by ljharb** [comment]
(Possibly related to #122)

**Comment by myuseringithub** [comment]
preserveSymlinks doesn't seem to work in Windows Symbolic link or Junction. Is there a problem with the implementation in the module ?

**Comment by ljharb** [comment]
@myuseringithub does node itself work with windows symlinks?

**Comment by mk-pmb** [comment]
I reproduced the problem and took an strace capture. The diff shows what really happened vs. what I'd expect to happen:

```diff
-stat64("/mnt/…/nodejs/modules/node_modules/lodash/package.json", …
+stat64("/mnt/…/nodejs/modules/lodash/package.json", …
 stat64("/mnt/…/nodejs/node_modules/lodash/package.json", …
 stat64("/mnt/…/node_modules/lodash/package.json", …
 stat64("/mnt/node_modules/lodash/package.json", …
 stat64("/node_modules/lodash/package.json", …
```

It seems `resolve` searches for modules in module directories inside of module search path directories, but not inside the module search path directories themselves.

**Comment by myuseringithub** [comment]
@ljharb Yes, I use symbolic link of type Junction, as it allows me to create symlinks that are supported between the host machine (Windows OS), and the Docker container (Linux OS) which I'm running the app from. In my setup both the host machine and container use JS scripts to run the project. 
Node's `require.resolve('<a symlink>')` returns the real path of the symlink as Node's command option `--reserve-symlink` is set to false by default.

**Comment by ljharb** [comment]
I'm unclear on what needs to be done here. Could anyone provide a repro repo, or better, a failing test case?

**Comment by mk-pmb** [comment]
Bug demo in GitLab Actions: https://github.com/mk-pmb/browserify-resolve-symlink-163

**Comment by ljharb** [comment]
@mk-pmb thanks - is there any way to repro it on the command line?

**Comment by ljharb** [comment]
@mk-pmb ah! resolve 1 has `preserveSymlinks: true` set by default. resolve _2_ has `preserveSymlinks: false` set by default.

Try setting `preserveSymlinks: false` explicitly (or try a resolve 2 prerelease).

**Comment by mk-pmb** [comment]
> is there any way to repro it on the command line?

Yes, if you run `demo.sh` in an environment similar enough to the GitHub Actions env.

> `readlink: illegal option -- m`

You'll need GNU coreutils 8.21 or later installed. Ubuntu ships it by default, so I use that in the GitHub Actions.

> Try setting `preserveSymlinks: false` explicitly (or try a resolve 2 prerelease).

Done in the `no-preserve-symlinks` branch, results are in.

**Comment by ljharb** [comment]
Looks like they're all passing there.

Sounds like this can be closed?

**Comment by ljharb** [comment]
```
pify?
41    node.js resolver: /…/browserify-resolve-symlink-163/mnt/projects/webdev/js/modules/pify/index.js
42    "resolve" module: /…/browserify-resolve-symlink-163/mnt/projects/webdev/js/modules/pify/index.js
    ```
    
Seems like it's good! Does that mean this can be closed?

**Comment by mk-pmb** [comment]
The first two tests are the part that had been easy to fix ever since. The bug in my opening post is reproduced in the 3rd test case, and it still fails:

```text
global-module-163?
    node.js resolver: /…/browserify-resolve-symlink-163/mnt/projects/webdev/js/secret_modules/global-module-163/dummy.js
    "resolve" module: Error: Cannot find module 'global-module-163' from '/home/runner/work/browserify-resolve-symlink-163/browserify-resolve-symlink-163/home/demo/my-cool-app'
```

**Comment by mk-pmb** [comment]
I see now why you thought it was about the pify path. I'll clarify the tutorial in the demo readme.

**Comment by ljharb** [comment]
the words "global module" concern me a bit; global modules aren't requireable or resolveable (unless you use the deprecated NODE_PATHS env var, which this package intentionally doesn't support and likely never will). Can you elaborate on that one?

**Comment by mk-pmb** [comment]
I'm not sure if my naming of "global" in the example is correct. I'm also not up-to-date on the deprecation. If you can determine the cause and conclude that the difference in the 3rd exampe is out of project scope, we shall instead check whether the readme could use better info about why.

**Comment by mk-pmb** [comment]
However, what I can provide, is to say I didn't write anything about `NODE_PATHS` in the example repo. Also `git grep -nFe NODE_PATH` came back empty, so it hasn't crept in.

**Comment by ljharb** [comment]
I'm able to cd into `home/demo/my-cool-app` and run `node app.js`, and `require.resolve` itself can't find `global-module-163` - which makes sense, since there's no `node_modules/global-module-163` present, in that directory or any above it. What do you expect will happen?

**Comment by mk-pmb** [comment]
I expect it will consider `~/.node_modules` at some stage, probably after `~/node_modules`.

**Comment by ljharb** [comment]
@mk-pmb it doesn't and shouldn't, no - `.node_modules` is never a thing.

Either way, in your repro repo there's no `global-module-163` anywhere, so it's *supposed* to fail to resolve, best I can tell.

**Comment by mk-pmb** [comment]
What do you mean by ".node_modules is never a thing."? It's still in current node master: [lib/internal/modules/cjs/loader.js](https://github.com/nodejs/node/blob/f7be6ab042059659caa1d5fd18e181f472b33f27/lib/internal/modules/cjs/loader.js#L1235)

```javascript
  if (homeDir) {
    ArrayPrototypeUnshift(paths, path.resolve(homeDir, '.node_libraries'));
    ArrayPrototypeUnshift(paths, path.resolve(homeDir, '.node_modules'));
  }
```

Which explains why on GitHub Actions, node.js can successfully resolve all examples. (See logs, or example output in readme). 

```text
global-module-163?
    node.js resolver: /…/browserify-resolve-symlink-163/mnt/projects/webdev/js/secret_modules/global-module-163/dummy.js
```


> Either way, in your repro repo there's no global-module-163 anywhere,

The resolving chain is (all inside repo):

`~/.node_modules` = `home/demo/.node_modules` = symlink to `../../mnt/projects/webdev/js/modules`
&rarr; `mnt/projects/webdev/js/modules` contains symlink `global-module-163` to `../secret_modules/global-module-163`
&rarr; `mnt/projects/webdev/js/secret_modules/global-module-163` contains `package.json`

**Comment by ljharb** [comment]
whoa, that was not a thing I was aware of.

`resolve` has no knowledge of those paths and isn't set up to use them, and I'm not sure why anybody else would. `$HOME` shouldn't have any node_modules.

**Comment by ljharb** [comment]
In other words, this issue has nothing to do with symlinks - it's about some kind of special `$HOME/.node_modules` path that nobody's ever mentioned in a decade of this package not supporting it :-) I'll update the title to reflect that.

(note that "global" means `npm root -g`; this home dir thing is something else)

**Comment by ljharb** [comment]
For history's sake: https://github.com/nodejs/node/commit/5a49f96505e48d2a1aa3a21233976f41fe1257ce#diff-cdd77182e73349d6c83fbbce1cccf6f15972fbece4dbd9c52eececf1ca3bfcd5R307-R308 is in every node version since basically ever.

**Comment by mk-pmb** [comment]
I updated my test project;
* Fix the naming of the module to be resolved via `~/.node_modules`
* Add test for `~/.node_libraries`
* Add test for an actual global module

**Comment by ljharb** [comment]
indeed; global things aren’t supposed to be requireable.

**Comment by ljharb** [comment]
The current workaround for this is to pass `[$HOME/.node_libraries, $HOME/.node_modules]` as the `paths` option.

**Comment by ljharb** [comment]
@mk-pmb can you confirm that https://github.com/browserify/resolve/pull/273 works for you? (or the equivalent change on 1.x)
