### ISSUE TITLE
support paths that do not start with ./

### ISSUE THREAD

**Issue by SeregPie** [browserify/resolve#165]
Hello. This is a really useful library. There is only one thing I wish.

```js
// throws error
resolve.sync('path/to/file', {basedir: '/home'});

// works
resolve.sync('./path/to/file', {basedir: '/home'});
```

**Comment by ljharb** [comment]
This is how node works; paths not starting in `.` or `/` are "bare" requires, and these are (effectively) always looked for in `node_modules`.

**Comment by SeregPie** [comment]
This is how `require` works.
`path.relative('/data/src', '/data/src/test')` will return `'test'` and not `'./test'`.
https://nodejs.org/api/path.html#path_path_relative_from_to

**Comment by ljharb** [comment]
@SeregPie note how you used `path.relative` there, which isn't the same as `require` or `require.resolve`? Try with `require.resolve`.

**Comment by SeregPie** [comment]
Ok. =(
