### ISSUE TITLE
Feasibility of dropping old Node.js versions

### ISSUE THREAD

**Issue by realityking** [browserify/resolve#168]
Because of a licensing issue with path-parse (see apiaryio/dredd#1058), I was curios how feasible it'd be to drop support for Node.js 0.6, 0.8 and 0.10 from this package. Nothing directly actionable here but I thought I'd share.

This would be a major release so it's not strictly necessary that all dependents have the same requirements but it'd obviously be beneficial if the most popular ones did - otherwise these popular modules would be cut off from fixes.

I did a quick check of the most 20 most popular dependents of `resolve` and what Node version they require:

| Package | Min. Node version |
| - | - |
| [eslint-plugin-import](https://www.npmjs.com/package/eslint-plugin-import) | 4.0 |
| [browserify](https://www.npmjs.com/package/browserify) | 0.8 |
| [tslint](https://www.npmjs.com/package/tslint) | 4.8 |
| [istanbul](https://www.npmjs.com/package/istanbul)* | 0.10** |
| [tape](https://www.npmjs.com/package/tape) | 0.8** |
| [@babel/core](https://www.npmjs.com/package/@babel/core) | 0.10*** |
| [react-scripts](https://www.npmjs.com/package/react-scripts) | 6 |
| [postcss-import](https://www.npmjs.com/package/postcss-import) | 4.5** |
| [eslint-plugin-node](https://www.npmjs.com/package/eslint-plugin-node) | 6 |
| [gulp-load-plugins](https://www.npmjs.com/package/gulp-load-plugins)* | 0.12** |
| [liftoff](https://www.npmjs.com/package/liftoff) | 0.8 |
| [rollup-plugin-node-resolve](https://www.npmjs.com/package/rollup-plugin-node-resolve) | 4** |
| [brfs](https://www.npmjs.com/package/brfs) | 0.8 |
| [rollup-plugin-commonjs](https://www.npmjs.com/package/rollup-plugin-commonjs) | 4**** |
| [grunt-cli](https://www.npmjs.com/package/grunt-cli) | 0.10 |
| [babel-plugin-module-resolver](https://www.npmjs.com/package/babel-plugin-module-resolver) | 4 |
| [browserify-shim](https://www.npmjs.com/package/browserify-shim) | ? |
| [proxyquire](https://www.npmjs.com/package/proxyquire) | 4** |
| [next](https://www.npmjs.com/package/next) | 4*** |
| [glslify](https://www.npmjs.com/package/glslify) | 0.8**** |

* Last release > 1 year ago
** Babel v7 will require Node.js >= 6.9
*** Inferred from CI config
**** Inferred from dependency versions

Dropping Node.js < 0.8 seems very feasible today but also doesn't change anything. 0,8 is not too far off, 0.10 seems like a bit of a tall order.

**Comment by ljharb** [comment]
I find no value in dropping support for old node versions - in fact, i find doing o to be harmful to the community.

This package will retain node compatibility for 0.6 for as close to forever as is possible, and should even work on 0.4.

The “issue” on path-parse is that the full license text is not included - while that’s important to fix, i would be shocked if any court interpreted the package as anything other than being MIT (per discussion on that PR).

If you are using a newer version of node, you can get around any licensing issue by simply replacing the path-parse files on disk in a postinstall script with `module.exports = require(‘path’).parse`, ensuring that the path-parse code doesn’t exist in your codebase.

**Comment by ljharb** [comment]
Happy to keep discussing, but I'm going to close for now.

**Comment by realityking** [comment]
Of course, this was really just an FYI.
