### ISSUE TITLE
number of npm users with publish abilities

### ISSUE THREAD

**Issue by jdalton** [browserify/resolve#169]
I noticed that this package is pretty popular and there may be a high number of users with the ability to publish it. This makes it appealing for attackers to try to compromise the package by way of one of the maintainers with publish rights who has [a weak password](https://github.com/ChALkeR/notes/blob/master/Gathering-weak-npm-credentials.md) or [other](https://eslint.org/blog/2018/07/postmortem-for-malicious-package-publishes)-[avenues](https://threatpost.com/attackers-use-typo-squatting-to-steal-npm-credentials/127235/).

<img width="377" src="https://user-images.githubusercontent.com/4303/44532159-48724e00-a6a7-11e8-8274-990137d531d7.png">

You can now require the package be published with 2FA [via the CLI](https://blog.npmjs.org/post/175861857230/two-factor-authentication-protection-for-packages) or npm website interface. npm doesn't currently indicate if the package requires 2FA so this may already be done for `resolve` but I figured I'd request it in case.

**Comment by ljharb** [comment]
I can lock that down, sure (it’s really just me publishing this one). all packages in the browserify org have all org members as publishers.

**Comment by ljharb** [comment]
`npx npmc@6.2.0-canary.1 access 2fa-required resolve` → `"ok"`

**Comment by jdalton** [comment]
Thanks! I've done a [follow-up request for `parse-path`](https://github.com/jbgutierrez/path-parse/issues/5) _(the only `resolve` dep)_ too.

**Comment by Heufiih** [comment]
Ok
