### ISSUE TITLE
TypeError: Cannot read property 'main' of undefined

### ISSUE THREAD

**Issue by ile** [browserify/resolve#179]
I'm getting this error with the 1.9.0. It works fine with 1.8.1.

The package where it stops at is this: https://github.com/k-components/k-connection-alert

```
TypeError: Cannot read property 'main' of undefined
    at loadAsDirectorySync (/home/app/myapp/node_modules/resolve/lib/sync.js:123:21)
    at Function.module.exports [as sync] (/home/app/myapp/node_modules/resolve/lib/sync.js:49:40)
    at Object.loadViewsSync (/home/app/myapp/node_modules/k-client/lib/files.js:21:26)
    at App.loadViews (/home/app/myapp/node_modules/k-client/lib/App.server.js:218:20)
    at App.component (/home/app/myapp/node_modules/k-client/lib/components.js:190:10)
    at Object.<anonymous> (/home/app/myapp/src/app/index.coffee:9:5)

```

**Comment by ljharb** [comment]
Now, it's worth noting that unless you specify `.coffee` as an extension, you won't be able to resolve this package - but this isn't the error you should be seeing. Thanks for the report, will fix ASAP!

**Comment by ljharb** [comment]
Can you provide the actual call to `resolve` you're making?

**Comment by ljharb** [comment]
(Separate from the best practice, which is to only publish transpiled code) using some kind of coffee-register would be required to require any coffeescript file, regardless of extension - the `resolve` package, however, only resolves `.js` by default regardless of how `module.extensions` has been modified, unless the `extensions` option overrides it. Can you provide the entire `require` call being made, including all options?

**Comment by ljharb** [comment]
Ahhhh, I see the problem. `packageFilter` is expected to return an object, and you have it returning `undefined` - if you added `return package` at the end, it'd be fine.

This should have broken in v1.8.1 as well - it's been the case for the entirety of v1, at least. Can you confirm that if you downgrade to resolve v1.8.1, the problem goes away?

**Comment by ljharb** [comment]
Closing; happy to reopen if that's not the case.
