### ISSUE TITLE
package.json is re-parsed repeatedly

### ISSUE THREAD

**Issue by yepitschunked** [browserify/resolve#185]
It seems like when we find a package.json we run it through JSON.parse every time:
https://github.com/browserify/resolve/blob/2321cd4b4e184f9c97f76ea50dd49b9e42927b93/lib/sync.js#L120

Seems like we could cache bodies we've seen before and avoid the re-parse in those cases. This would be especially helpful in a large repo with a single package.json.

**Comment by ljharb** [comment]
There’s no guarantee that the file is unmodified between calls.

**Comment by ljharb** [comment]
Closing, per https://github.com/browserify/resolve/pull/186#issuecomment-492922401
