### ISSUE TITLE
1.11.1 breaks rollup-plugin-node-resolve

### ISSUE THREAD

**Issue by bterlson** [browserify/resolve#194]
A recent [change to handling shadowed modules](https://github.com/browserify/resolve/pull/148) has broken rollup-plugin-node-resolve. I [filed an issue](https://github.com/rollup/rollup-plugin-node-resolve/issues/222) on the plugin to adapt to the new version as I agree the fix is the right thing to do long term.

However, before a fix to the plugin materializes, we might be able to prevent more people tumbling down this rabbit hole by making sure people aren't broken in the meantime. I think a breaking change like this should be done in a major version. Can I suggest either reverting this fix and releasing 1.11.2 or moving the next pointer back to 1.11.0? The revert seems cleaner to me, and more likely to get people out of a broken state by simply updating their packages, though I'm not entirely sure how moving the next pointer impacts users who have already upgraded to 1.11.1.

**Comment by ljharb** [comment]
As a short-term fix, I've set `1.11.0` as "latest" (`1.11.1` is now "next"), so that fresh installs shouldn't run into the problem.

Certainly anyone who's already depending on `^1.11.1`, or who has it in a lockfile, likely will hit this problem unless they manually downgrade - that's the group who a `1.11.2` would benefit.

If the rollup plugin doesn't get a fix in very soon, I'll probably do the revert, but it'd be really nice to avoid having to revert a legitimate bugfix just because someone is relying on the broken behavior :-/

**Comment by bterlson** [comment]
@ljharb please [re-enable spacebar heating](https://xkcd.com/1172/).

**Comment by bterlson** [comment]
Just FYI, https://github.com/rollup/rollup-plugin-node-resolve/issues/222 was fixed with https://github.com/rollup/rollup-plugin-node-resolve/issues/223. Once that's released, you could probably move latest up again 😊

**Comment by ljharb** [comment]
v5.0.2 is released; can you confirm that even with v1.11.1 installed, the bug is fixed?

**Comment by ljharb** [comment]
Closing pending further reports.

**Comment by mikeharder** [comment]
@ljharb: Sorry for the delay getting back to you.  We have verified that `rollup-plugin-node-resolve@5.0.2` is compatible with `rollup@1.11.1` in a minimal repro project.

We are still working to update our full repo to `rollup-plugin-node-resolve@5.0.2` and `rollup@1.11.1`.  Once this is done, we will re-open this issue if there are problems.

Are you going to move the `latest` pointer back to `1.11.1`?

**Comment by ljharb** [comment]
@mikeharder now that i have a confirmation, yes :-)

**Comment by ljharb** [comment]
sigh, looks like it broke another rollup package: https://github.com/rollup/rollup-plugin-commonjs/issues/394
