### ISSUE TITLE
packageFilter paths should be realpathed with preserveSymlinks: false

### ISSUE THREAD

**Issue by bterlson** [browserify/resolve#201]
Right now a package filter is called with potentially symlinked paths.

**Comment by ljharb** [comment]
Thanks! I'll take a look, but a PR with a test case would be super helpful.

**Comment by bterlson** [comment]
@ljharb will try to put up a PR, but test cases are really annoying to make when symlinking is involved. Here's how to repro, though:

Directory structure like:

```
common
  node_modules
    mod-a
project
  node_modules
    mod-a -> ..\..\common\node_modules\mod-a
```

cd into project, open a node console, and enter:

```
> require('resolve').sync('mod-a', {
    preserveSymlinks: false,
    packageFilter (_, path) { console.log(path) }
  });
// console logs a symlinked path for the package json, but returns a realpath as expected.
```

**Comment by ljharb** [comment]
@bterlson in your example, there's no `package.json`s - `packageFilter` only kicks in when there is one. Do you also have a package.json inside `mod-a`?

**Comment by bterlson** [comment]
@ljharb yessir, and main files, although that part is probably not necessary to highlight the problem.

**Comment by ljharb** [comment]
Writing this failing test exposed two more unrelated bugs that I'll need to test and fix separately :-) This one's coming up shortly tho!

**Comment by ljharb** [comment]
v1.12.1 is released.

Note that this includes a bugfix where `packageFilter` was incorrectly getting called with the documented 2nd arg omitted; any sync packageFilter callbacks will likely need to be altered.
