### ISSUE TITLE
CHANGELOG missing

### ISSUE THREAD

**Issue by MichaelDeBoey** [browserify/resolve#208]
I just saw the package is updated to `v1.15.0`, but I can't find any CHANGELOG to check out the changes.

Would you guys be so kind to provide us with a decent CHANGELOG please? 🙂

Thanks for all your hard work! 🙂

**Comment by ljharb** [comment]
The tagged release commit has them: https://github.com/browserify/resolve/releases/tag/v1.15.0 which is also visible if you click GitHub’s “releases” button. at the root of the repo.

**Comment by MichaelDeBoey** [comment]
Hmm that's strange.
When I watched the [releases](https://github.com/browserify/resolve/releases), I didn't see any release notes.
<img width="377" alt="Schermafbeelding 2020-01-22 om 17 16 03" src="https://user-images.githubusercontent.com/6643991/72911798-efdf2e80-3d3a-11ea-998c-12bca86f3b6e.png">

**Comment by ljharb** [comment]
expand the ellipsis next to each tag.
