### ISSUE TITLE
onwrite deprecated?

### ISSUE THREAD

**Issue by farhanRIT** [browserify/resolve#213]
Hi, I get this warning message when building my project:

(!) The "onwrite" hook used by plugin node-resolve is deprecated. The "generateBundle/writeBundle" hook should be used instead.

**Comment by ljharb** [comment]
That seems like it's for a browserify hook; `resolve` is a standalone package.

**Comment by farhanRIT** [comment]
> That seems like it's for a browserify hook; `resolve` is a standalone package.
Sorry I posted in a wrong package/git. New to npm packages and not sure sure how to search for exact package through npm. A lot of similar names.
