### ISSUE TITLE
Add option to ignore core packages and search for alternative in node_modules

### ISSUE THREAD

**Issue by yuri-karadzhov** [browserify/resolve#215]
Add option to ignore core packages and search for alternative in node_modules that is important for browser builds. e.g. `url` package is being detected like core package even if it is installed from npm `npm i url`

**Comment by ljharb** [comment]
Browser builds already have a mechanism for this (which the browser-resolve package uses); separately, if know you want the local one, try `resolve('url/')`. What's your use case?

**Comment by yuri-karadzhov** [comment]
Thanks! It works with `/`. I'm working on smart server that modularise and build packages with no configuration required https://hqjs.org
