### ISSUE TITLE
Cannot find module 'tape'

### ISSUE THREAD

**Issue by rizowski** [browserify/resolve#219]
I am getting this error when I try to start my app. It's bubbling up from XO since it uses multiple dependencies that rely on resolve.

```
Error: Cannot find module 'tape'
Require stack:
- /Users/rizowski/git/work/events-service/node_modules/resolve/test/resolver.js
```

Test cases:
  - reverted from node 12 to 10
  - switched to xo version 0.26 which was well before this issue
  - switched to yarn in case npm is causing the issue
  - deleted lock files and node_modules for each test

**Comment by ljharb** [comment]
That doesn’t make sense; that’s one of resolve’s tests. Why would you be evaluating it?

**Comment by rizowski** [comment]
Beats me. That's why I'm here. haha 

All I did was install XO. I've been pounding my head on this issue for the last 3 days thinking maybe it had something to do with docker volumes and windows and it not installing correctly. But I ported the project over to my mac, duplicated the issue in the container and on my machine.

I can get the error to go away if I install tape or uninstall XO. I've tried moving back a version on XO since they released 4-8 days ago but that also didn't fix it.

**Comment by ljharb** [comment]
xo is a linter i believe, perhaps it’s linting files in node_modules? If so, configure it not to.

**Comment by rizowski** [comment]
Hmm maybe, it should be ignoring that directory by default. I'll see if that is the issue.

**Comment by ljharb** [comment]
That’s also true (assuming your app doesn’t use xo). What is your app’s start command?

**Comment by rizowski** [comment]
I use this for local:
```
nodemon -e js,graphql,json .
```

Or this for production
```
node .
```

So nothing too fancy. Both produce the issue.

**Comment by rizowski** [comment]
Ha I just found it. I had a bad glob pattern in my project. It was `./**/*resolver.js` I must have missed that it was loading from the root of my project so it was looking in node_modules. 

Crazy how things can be figured out in an hour of talking to someone you don't know after staring at an issue for 3 days. 😆 Thanks again 👋
