### ISSUE TITLE
Conditional use of `require('module').builtinModules`?

### ISSUE THREAD

**Issue by coreyfarrell** [browserify/resolve#221]
I was just reading the comments in https://github.com/nodejs/node/pull/31553 and wondering if `resolve` could conditionally ask the core for the list of core modules?  The idea would be for lib/core.js to have a branch for if `builtinModules` is defined and bypass core.json in node.js `^6.13 || ^8.10 || >=9.3.0`.  This would make lib/core.json 'legacy only' and it would never need to be updated again since (I think) no core modules will ever be added to any version of node.js which does not publish the list on it's own.

**Comment by ljharb** [comment]
Nope, because that list isn't complete (i forget if it has extras or is missing some) - see the test: https://github.com/browserify/resolve/blob/8dba8463b0621cf3639f6747dd088d84b1c0d833/test/core.js#L64-L70

**Comment by ljharb** [comment]
Also, `resolve` is used in browsers, where `require('module')` does not exist - I'd rather keep core.json as the identical source of truth in both than have a risk of drift between node and non-node.

**Comment by coreyfarrell** [comment]
I checked the current (or maybe recent) release of resolve against node.js v14.0.0-rc.3, the only difference was that resolve didn't know about `fs/promises` yet.

Understood about browser compatibility though, that's logical.

**Comment by ljharb** [comment]
The current one, v1.16.0, knows about fs/promises in node 14+. RCs don't count, and node 14 isn't out yet :-)
