### ISSUE TITLE
ReferenceError: process is not defined

### ISSUE THREAD

**Issue by Profesor08** [browserify/resolve#237]
webpack 5 does no longer include a polyfill for this Node.js variable. Avoid using it in the frontend code.

https://webpack.js.org/migrate/5/#run-a-single-build-and-follow-advises

```
var current = (process.versions && process.versions.node && proce  ss.versions.node.split('.')) || [];
                ^
  ReferenceError: process is not defined

- index.tsx:46059 Object../node_modules/resolve/lib/core.js
```

**Comment by ljharb** [comment]
A non-broken node module bundler always provides process. You can unbreak webpack 5 by using the ProvidePlugin to inject node globals.
