### ISSUE TITLE
Publish new version of 1.x branch to npm with updated dependency of path-parse

### ISSUE THREAD

**Issue by shaunek** [browserify/resolve#246]
The path-parse package dependency [had a reported security vulnerability](https://snyk.io/vuln/SNYK-JS-PATHPARSE-1077067) and they have subsequently published an update (from parse-path v 1.0.6 to 1.0.7).

Currently the 1.x branch in this repository has updated to the secure version of the path-parse package (see commit d7f5c3e), however it does not appear that this has been published to npm yet. I would like to request that a new 1.x version be published to npm.

Thx

**Comment by ljharb** [comment]
This isn’t needed, because of how semver ranges work.

Either way, it's not an actual vulnerability for `resolve`. Duplicate of #240. Duplicate of #243. Duplicate of #244.

**Comment by shaunek** [comment]
Agreed. Apologies for the duplicate ticket. Thanks for the support
