### ISSUE TITLE
Multi level "exports" not supported?

### ISSUE THREAD

**Issue by achingbrain** [browserify/resolve#250]
The [multiformats](https://www.npmjs.com/package/multiformats) module has the following fields in it's `package.json`:

```
{
  // ...other stuff
  "main": "./cjs/src/index.js",
  "browser": {
    ".": "./cjs/src/index.js",
    "./basics": "./cjs/src/basics.js",
    "./bases/base16": "./cjs/src/bases/base16.js"
    // ...other stuff
  },
  "exports": {
    ".": {
      "browser": "./esm/src/index.js",
      "require": "./cjs/src/index.js",
      "import": "./esm/src/index.js"
    },
    "./basics": {
      "browser": "./esm/src/basics.js",
      "require": "./cjs/src/basics.js",
      "import": "./esm/src/basics.js"
    },
    "./bases/base16": {
      "browser": "./esm/src/bases/base16.js",
      "require": "./cjs/src/bases/base16.js",
      "import": "./esm/src/bases/base16.js"
    }
    // ...other stuff
  }
}
```

and the following directory structure:

```
multiformats
|-- cjs
|    +-- src
|         |-- index.js
|         |-- basics.js
|         +-- bases
|              +-- base16.js
|-- esm
|    +-- src
|         |-- index.js
|         |-- basics.js
|         +-- bases
|              +-- base16.js
|-- src
|    |-- index.js
|    |-- basics.js
|    +-- bases
|         +-- base16.js
```

When using browserify on a project that depends on multiformats, I see errors when trying to require anything greater than one level deep in the module:

```js
const mf = require('multiformats')
// ok
```

```js
const basics = require('multiformats/basics')
// ok
```

```js
const basics = require('multiformats/basics/base16')
// Error: Can't walk dependency graph: Cannot find module 'multiformats/bases/base16' from '/path/to/index.js'
//     required by /path/to/index.js
//     at /path/to/node_modules/resolve/lib/async.js:137:35
//     at processDirs (/path/to/node_modules/resolve/lib/async.js:291:39)
//     at isdir (/path/to/node_modules/resolve/lib/async.js:300:32)
//     at /path/to/node_modules/resolve/lib/async.js:25:69
//     at FSReqCallback.oncomplete (fs.js:183:21)
```

Is this intentional?  I can't see where this module consults the `exports` field (though it's been a long day) or is it unsupported?

**Comment by ljharb** [comment]
`resolve` does not yet support the "exports" field in any way; see #224.

Regardless, for backwards compatibility, packages like multiformats should be mimicking the "exports" structure in a CJS-compatible directory structure - at which point, tools like resolve will Just Work.

**Comment by achingbrain** [comment]
After digging a bit deeper this has nothing to do with the `"exports"` field.  Browserify won't consult the `browser` map in `package.json` to see if a file should be overridden if it can't resolve the original file in the first place.

That is, you can't use `browser` values as a hint to Browserify as to where to look for the file for a given path that's been `require`d in the same way you can with `"exports"`.

One thing is that the file at the given path doesn't need to actually have any content, it just needs to exist, and node will take `exports` over `browser` so there's no danger of it importing the wrong file.

**Comment by ljharb** [comment]
New node will, yes, but old node won't use `exports` or `browser` - so the "exports" structure should still be represented in actual requireable CJS files in the filesystem.

**Comment by achingbrain** [comment]
This has been fixed by the linked ipjs PR
