### ISSUE TITLE
Prioritize moduleDirectory array elements

### ISSUE THREAD

**Issue by ATheCoder** [browserify/resolve#251]
I'm not sure if this is expected behavior for everyone or not.

But when I was using [Jest](https://github.com/facebook/jest), I supplied the array `['node_modules', '.']` to the `moduleDirectories` option in the Jest config file.

What I expected was that `node_modules` would have a priority over `.`, meaning if a module exists in both `node_modules` and the local folder, it should get imported from `node_modules` and not from the local folder.

This expectation was later shown to be wrong because of an `Maximum call stack size exceeded` error in Jest when importing the [IORedis](https://github.com/luin/ioredis) module.

More investigation led me to understand that IORedis has a [debug.js](https://github.com/luin/ioredis/blob/master/lib/utils/debug.ts) file that imports the [debug](https://www.npmjs.com/package/debug) npm module, however because of my `moduleDirectories` setup, the debug.js file would import itself instead of the npm module causing an infinite loop and later a `maximum call stack size exceeded` error.

Changing `moduleDirectories` to `['node_module`]` would fix the issue.

Later when investigating why this happens I came across the `getNodeModulesDirs` function inside `resolve`.

Supplying `['node_modules', '.']` to the `modules` argument and `/someFolder/build/utils` to the `absoluteStart` argument would return the following:

```
[
  '/someFolder/build/utils/node_modules',
  '/someFolder/build/utils',
  '/someFolder/build/node_modules',
  '/someFolder/build',
  '/someFolder/node_modules',
  '/someFolder',
  '/node_modules',
  '/'
]
```

However I would expect it to be:

```
[
  '/someFolder/build/utils/node_modules',
  '/someFolder/build/node_modules',
  '/someFolder/node_modules',
  '/node_modules',
  '/someFolder/build/utils',
  '/someFolder/build',
  '/someFolder',
  '/'
]
```

Notice how `node_modules` is prioritized over the `.`

I believe node works in the same manner because when using node `14` I did not have this problem while using IORedis but since Jest uses **resolve** to resolve dependencies this resulted in me having this problem.

**Comment by ljharb** [comment]
nodeModuleDirs is applied in each directory, so I’m not sure why you’d have that expectation.

node doesn’t work in this manner at all, because it doesn’t allow the resolution algorithm to be overridden.
