### ISSUE TITLE
Support browser filed

### ISSUE THREAD

**Issue by anschm** [browserify/resolve#254]
I am using jest for my unit tests. Jest provides a default resolver which is used by nx. Now I have a lib which provides node and browser source code by using the browser field to override the main field. In my tests I would like to use the browser sources and it seems that the browserify resolver which is used by the jest default resolver doesn't support this. I know there is a browser-resolver which wrappes the resolver, but most frameworks using resolver very deep inside and its not handsome to write a own resolver to switch between the browser-resolver and resolver.

**Comment by ljharb** [comment]
`resolve` matches node, which doesn't look at the browser field.

You want https://www.npmjs.com/package/browser-resolve for that.

Jest would need to provide a way to configure this, even if `resolve` added it behind an option.
