### ISSUE TITLE
Use throwIfNoEntry for default isFile and isDirectory

### ISSUE THREAD

**Issue by markjm** [browserify/resolve#255]
Similar to https://github.com/webpack/enhanced-resolve/issues/316

Performance of skipping error generation is significant (mini-benchmark present in above issue) and the API is backward compatible. 

Since this project doesnt use graceful-fs, this change should be available to make right now. I do somewhat worry about usage of monkeypatched graceful-fs, though, as that seems to fall into a weird grey area of deciding semver.

**Comment by ljharb** [comment]
I'm not sure I understand what you're proposing.

We use `fs`, not `graceful-fs`, and it definitely seems very strange to add an option node doesn't support just in case someone is using graceful-fs to patch the builtin.

**Comment by markjm** [comment]
Sorry I should clarify:

throwIfNoEntry is a node supported option that is much more performant than letting statSync throw and immediately catch it (https://nodejs.org/api/fs.html#fsstatsyncpath-options). For that reason, I believe we should use that option here. The option is a no-op in older versions of node, so long as you just keep the try/catch block the same. I will create a PR to showcase the change.

My only concern with doing this change is that *if* a consumer is using a monkeypatched graceful-fs, they may run into issues with this change. Since this package does not specify graceful as a dependency, I dont think it is really a "breaking change", but its worth understanding that it may still break some people using a semi-common patch.

**Comment by ljharb** [comment]
It is none of our concern what someone does with graceful-fs; that's not a supported use case since it involves monkeypatching.

**Comment by markjm** [comment]
@ljharb I have linked the change here
