### ISSUE TITLE
Dependency package "path-parse - 1.0.6" is reported as vulnerable by Whitesource scan

### ISSUE THREAD

**Issue by RajakumarSidhan** [browserify/resolve#258]
Hi, 
While running whitesource scan it reported that one of the dependent package as vulnerable.

![image](https://user-images.githubusercontent.com/22787486/143655647-af7601fb-0ad2-455d-aefa-feac2dce3165.png)

Reporting the same and kindly provide a fix;

Regards
Raja

**Comment by ljharb** [comment]
There's no fix required; path-parse v1.0.7 is not vulnerable, and resolve uses `^` - a semver range, which means you can upgrade the transitive dep yourself.

Duplicate of #252. Duplicate of #247. Duplicate of #240. Duplicate of #243. Duplicate of #244. Duplicate of #246.
