### ISSUE TITLE
Error with incorrectly closed json

### ISSUE THREAD

**Issue by augustofnl** [browserify/resolve#265]
Could you please fix this json closure?

![image](https://user-images.githubusercontent.com/2956310/148289952-161ec222-7bc6-4ec7-a618-04f6dcc56564.png)

**Comment by ljharb** [comment]
Nope, it's not broken. It's an intentionally malformed package.json file for testing purposes (note the filename).

If it's causing issues for you, detailing those might be helpful.

See also #262.
