### ISSUE TITLE
Fix non-valid values in .editorconfig file

### ISSUE THREAD

**Issue by funnydino** [browserify/resolve#272]
Hello.
In .editorconfig file, _insert_final_newline=off_ is not valid value.
[editorconfig-checker](https://www.npmjs.com/package/editorconfig-checker) shows fatal error at this value.
I checked the whole file at [editorconfig website](https://editorconfig.org/), and found other not valid values, and fixed them.
I don't have permissions to create pull request, so here is my suggested solution:
for `indent_style`, `indent_size` and `insert_final_newline` change the _off_ value at _unset_.

**Comment by ljharb** [comment]
`editorconfig-checker` is old and outdated; i use npmjs.com/eclint which does support those values. There's no point in validating the editorconfig of third-party code, so I'm not sure how this came up.

Everybody has permission to make a pull request - you fork the repo, and make a PR from your fork.
