### ISSUE TITLE
v1.22.1 patch request

### ISSUE THREAD

**Issue by pos777** [browserify/resolve#285]
Is it possible to publish patch v1.22.1?
This is required to fix https://github.com/browserify/resolve/issues/283.

**Comment by ljharb** [comment]
Filing a new issue for this is just spam/noise; I'm well aware it needs to be published, but I have a personal life, and it's [quite busy right now](https://twitter.com/ljharb/status/1536791700856872965).

**Comment by pos777** [comment]
@ljharb, I am sorry -  did not want to disturb you with this issue. I just wanted to apply a patch here - https://github.com/rollup/plugins/tree/master/packages/node-resolve. I didn't know that you're the only one who can do this. So I created this issue in hope that someone else can publish a patch. 
Hope everything will be alright soon.

**Comment by ljharb** [comment]
v1.22.1 is released.
