### ISSUE TITLE
Reference to malicious package monorepo-symlink-test causing security scan to fail

### ISSUE THREAD

**Issue by reify-thomas-smith** [browserify/resolve#288]
The file [test/resolver/multirepo/package.json](https://github.com/browserify/resolve/blob/093a9d88db0e8710fc8774b17598ee58caf12169/test/resolver/multirepo/package.json) is causing JFrog's vulnerability scanner to flag resolve because the name field is the name of a malicious package. This is definitely JFrog's fault and not resolve's, but if it's breaking for us, it's probably breaking for others.

**Comment by ljharb** [comment]
Indeed; I'm glad `resolve` is exposing the many "security" tools out there that are broken.

A scanner that even looks at package files that are only used in development of the package, and never referenced in production, will produce lots of false positives that distract from meaningful reports.

In particular, the package has `private: true`, and thus has no relationship to https://www.npmjs.com/package/monorepo-symlink-test, so I'd report this to JFrog with some urgency.

**Comment by oscarduignan** [comment]
@ljharb with this, I wonder with this if the test files could be excluded from the package in npm - do they need to be distributed? Assuming they are from looking into the package using unpkg https://unpkg.com/browse/resolve@1.22.1/test/

**Comment by ljharb** [comment]
Yep! They forever do, because `npm explore foo && npm install && npm test` should always work.

**Comment by oscarduignan** [comment]
cool, thank you @ljharb for the quick response 🙌
