### ISSUE TITLE
Remove npm package monorepo-symlink-test (contains malicious code)

### ISSUE THREAD

**Issue by muhanator** [browserify/resolve#291]
npm package monorepo-symlink-test is used in https://github.com/browserify/resolve/blob/093a9d88db0e8710fc8774b17598ee58caf12169/test/resolver/multirepo/package.json#L2-L4

should be removed as it was found to contain malicious code and was removed from the registry by the npm security team. Anybody using npm package resolve:1.22.1 (latest version of resolve) has this in their code and can be at risk.
see https://www.npmjs.com/package/monorepo-symlink-test
![image](https://user-images.githubusercontent.com/26660603/186450471-f944db64-d9b0-4549-b053-c51e3448cff6.png)

**Comment by ljharb** [comment]
This package.json has `private: true`, because it has nothing to do with the malicious package in question. If your security analysis tool is reporting it, it's broken, and you should file a bug on it. There is zero risk here.

See #290.
