### ISSUE TITLE
Question around dummy packages in monorepo test

### ISSUE THREAD

**Issue by plygrnd** [browserify/resolve#292]
Hi folks,

We came across [@my-scope/package-a](https://github.com/browserify/resolve/tree/main/test/resolver/multirepo/packages/package-a/package.json) and [@my-scope/package-b](https://github.com/browserify/resolve/tree/main/test/resolver/multirepo/packages/package-b/package.json) when reviewing Resolve for internal use at my employer. Does the Browserify team own the `@my-scope` scope on NPM? I ask because we want to rule out the possibilty of dependency confusion within Resolve's test suite.

**Comment by ljharb** [comment]
Nope - their package.json has private:true, so their names don’t matter.

**Comment by plygrnd** [comment]
@ljharb Thanks, thought as much but I wanted to check. _Someone_ owns `@my-scope` on NPM, is why I asked; there were some concerns internally about someone publishing `package-[a|b]` on NPM and causing problems with Resolve, but I think that's highly unlikely.

**Comment by ljharb** [comment]
Those concerns are incorrect; nothing with private:true can be published, and a package.json in a test fixture isn't part of `npm install` so there's zero chance of pulling a same-named package from a registry.
