### ISSUE TITLE
Please make async resolve mockable with pure sinon

### ISSUE THREAD

**Issue by art-alexeyenko** [browserify/resolve#293]
If you have a function using resolve and invoking callback, i.e.:
```
resolve(path, options, (error, result) => {
//do things
}
```

and attempt to unit test the callback with [sinon](https://sinonjs.org/releases/latest/stubs/):
```
import * as resolve from 'resolve';
...
sinon.stub(resolve, 'default').callsArgWith(2, null, mockResult);
```

The stub will fail with error:
`Cannot redefine property: default`
Which is expected - since resolve function is not marked as default export. Instead it is a default export in a non-explicit way:
```
var async = require('./lib/async');
async.core = require('./lib/core');
async.isCore = require('./lib/is-core');
async.sync = require('./lib/sync');

module.exports = async;
```

While it's possible to mock sync and isCore exports (stub(resolve, 'sync')), async implementation is not reachable this way.
Please consider changing the way export is done so that async implementation could also be mocked.

**Comment by ljharb** [comment]
sinon is for mocking object properties, not for mocking modules. `import * as` produces, by spec, a frozen module namespace object, so it should always be impossible to mock things on it - if it is possible, you're in a broken environment.

Module mocking requires a very different approach than sinon.

In general, I'd encourage you to avoid mocking, and to actually put the thing you want resolved on the filesystem.
