### ISSUE TITLE
Unexpected end of input, expected the token `}`

### ISSUE THREAD

**Issue by AndyFang36** [browserify/resolve#294]
```
Error node_modules/resolve/test/resolver/malformed_package_json/package.json:2:1

Unexpected end of input, expected the token `}`
   2|
```

**Comment by ljharb** [comment]
I'm confused; this is a test file inside this package, it's intentionally malformed, and literally nothing should be touching it. Perhaps you're using a tool which is incompetently and naively evaluating all package.json files present in node_modules, even files that your code and tools will never use?

**Comment by ljharb** [comment]
I believe this is a duplicate of #274; duplicate of #266; duplicate of #265; duplicate of #262.

**Comment by AndyFang36** [comment]
oh, thanks.
