### ISSUE TITLE
Question: NPM version 1.22.3 is published but 1.22.2 is marked as `latest`

### ISSUE THREAD

**Issue by akphi** [browserify/resolve#298]
Hi,

I'm upgrading my package using interactive upgrader tool like `yarn` and I realized that while `1.22.3` is published, `1.22.2` is marked as latest on `NPM`, is this intended? If not, could you please update the `latest` alias to point at `1.22.3`, thank you so much!

**Comment by ljharb** [comment]
Yes, it's quite intended - that never happens by accident. See #297.
