### ISSUE TITLE
monorepo-symlink-test GHSA-2jcg-qqmg-46q6 Vulnerability

### ISSUE THREAD

**Issue by castafab** [browserify/resolve#303]
Hi , using the grype Scan Vulnerabilities tool was possible to detect a vulnerability in one of the dependencies that are used by you.

That dependency is in a package.json file inside of the rest->resolver->multirepo->package.json in the node_module from the resolve library.

This dependency that contains the vulnerability is the monorepo-symlink-test which was also already removed from the npm library (https://www.npmjs.com/search?q=symlink-test) you can check the readme on that page that was removed because contains malicious code.

Do you have some predictions to remove this dependency from your list of dependencies?

**Comment by mferreira3** [comment]
I'm having the same issue, would be glad if someone could take a look on this considering the severity of it 😕

**Comment by ljharb** [comment]
This is not a vulnerability, full stop. This is test code that is never used in production.

In fact, this package isn't even the same package as `monorepo-symlink-test`, that's just what i named it - it has `private: true` so it can't even be published.

So, your vulnerability scanner has broken heuristics, and I wouldn't trust its results.

**Comment by saintmalik** [comment]
i think this a false positive scan result from the grype scanner

**Comment by saintmalik** [comment]
I have digged to, leads to no point, the only package closer to be the one
holding this bug is something GitHub package

**Comment by ljharb** [comment]
@mfrye-aisera i could, but then people wouldn't discover that their "security scanner" fails to understand the semantics of the ecosystem it's trying to secure.

**Comment by mfrye-aisera** [comment]
@ljharb totally agree. I'm not a fan of our security scanner as I've already it found that it missed other more important stuff. I've already flagged this internally as not an issue, so I think we're good here. 

My comment was more for you, as I assume you're going to be continually annoyed with requests about this as orgs slowly discover the issue. So the easiest fix is to just change the name of the module, right?

**Comment by ljharb** [comment]
thanks, i appreciate your concern :-) i'll keep it this way for the time being, but certainly would rename it if it ever exceeds my tolerance for such things.
