### ISSUE TITLE
Resolve monorepo-symlink-test vulnerable package

### ISSUE THREAD

**Issue by frabbiDAndT** [browserify/resolve#304]
Grype scan is giving the following error:

NAME                                INSTALLED     FIXED-IN  TYPE  VULNERABILITY                SEVERITY 
monorepo-symlink-test  0.0.0                npm                      GHSA-2jcg-qqmg-46q6  Critical 

See more details:
https://snyk.io/advisor/npm-package/monorepo-symlink-test

Please fix the issue in:
https://github.com/browserify/resolve/blob/main/test/resolver/multirepo/package.json

**Comment by ljharb** [comment]
It's not actually an issue with this package, altho it does mean Grype is incompetent and you shouldn't use it - the package.json has private: true, the fact that the `name` field is the same is irrelevant.

Duplicate of #303. Duplicate of #291. Duplicate of #288.
