### ISSUE TITLE
`npx resolve` errors

### ISSUE THREAD

**Issue by vvscode** [browserify/resolve#315]
I have the error, so I added some debug info upfront:

```js
console.log({
    npm_lifecycle_script: process.env.npm_lifecycle_script,
    _: process.env._,
    __filename
})

if (
    String(process.env.npm_lifecycle_script).slice(0, 8) !== 'resolve '
    && (
        !process.argv
        || process.argv.length < 2
        || (process.argv[1] !== __filename && fs.statSync(process.argv[1]).ino !== fs.statSync(__filename).ino)
        || (process.env._ && path.resolve(process.env._) !== __filename)
    )
) {
    console.error('Error: `resolve` must be run directly as an executable');
    process.exit(1);
}
```

that gives me:

```js
{
  npm_lifecycle_script: 'resolve',
  _: '/Users/v.vanchuk/repo/test/node_modules/.bin/resolve',
  __filename: '/Users/v.vanchuk/repo/test/node_modules/resolve/bin/resolve'
}
```

I failed to follow the logic in this place
- when `npm_lifecycle_script` can have space at the end?
- why in general you make this restriction? (what's the purpose?)

Hope you can help / clarify this moment =)

Thanks in advance

**Comment by ljharb** [comment]
I'm a bit confused, can you clarify how you're getting this error?

**Comment by vvscode** [comment]
Sure =)

I just created new empty project 
```package.json
{
  "name": "resolve-demo",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "resolve": "^1.22.4"
  }
}
```

and installed dependencies with `yarn`

and inside I do run `npx resolve`

[resolve-demo.zip](https://github.com/browserify/resolve/files/12611768/resolve-demo.zip)

**Comment by ljharb** [comment]
aha, thanks :-) so, the bug is that it doesn't work with npx.

**Comment by vvscode** [comment]
I'm happy to help with the fix if you clarify the logic =)

shouldn't

```ts
String(process.env.npm_lifecycle_script).slice(0, 7) !== 'resolve'
```

solve the issue? (I didn't get that space at the end at all)

**Comment by vvscode** [comment]
about workaround: 

I added to package.json script
```
"scripts": {
       "resolve": "./node_modules/resolve/bin/resolve"
}
```

and run it with `npm run resolve` / `yarn run resolve`

just in case someone else faced the issue

**Comment by ljharb** [comment]
There'll be no need for that workaround; i'll have a release cut momentarily.

**Comment by ljharb** [comment]
v1.22.5 is published.

**Comment by vvscode** [comment]
it works. Thanks

**Comment by vvscode** [comment]
@ljharb just for my understanding - is this limitation to have correct argv and have no errors on processing params?

**Comment by ljharb** [comment]
And to ensure it can’t be required/imported.

**Comment by vvscode** [comment]
```js
function isEntryPoint() {
  return require.main === module;
}
```
might be more relyable solution for this

**Comment by ljharb** [comment]
`require.main` is deprecated and something that should never, ever have existed; i'm not going to use it.

**Comment by vvscode** [comment]
Can you link some information about it? 
I checked node@20 docs and see it is there without any deprecation notes

https://nodejs.org/api/modules.html#accessing-the-main-module

**Comment by vvscode** [comment]
More than that 

https://nodejs.org/api/deprecations.html#dep0138-processmainmodule

<h4 id="DEP0138" style="box-sizing: border-box; font-size: 1.5rem; font-weight: 700; line-height: inherit; position: relative; margin: 1.5rem 0px 1rem; text-rendering: optimizelegibility; padding-right: 40px; color: rgb(255, 255, 255); font-family: Lato, &quot;Lucida Grande&quot;, &quot;Lucida Sans Unicode&quot;, &quot;Lucida Sans&quot;, Verdana, Tahoma, sans-serif; font-style: normal; font-variant-ligatures: none; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(9, 12, 21); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">DEP0138:<span> </span><code style="box-sizing: border-box; font-family: inherit; font-size: 1.5rem; line-height: 1.5rem; margin: 0px; padding: 1px 3px; color: var(--grey-smoke); background-color: var(--background-color-highlight); border-radius: 2px;">process.mainModule</code><span style="box-sizing: border-box; position: absolute; display: block; top: 0px; right: 0px;"><a class="mark" href="https://nodejs.org/api/deprecations.html#dep0138-processmainmodule" id="dep0138-processmainmodule" style="box-sizing: border-box; color: var(--color-text-mark); text-decoration: none; font-weight: 700; scroll-margin-top: 55px; border-radius: 2px; padding: 1px 3px; position: absolute; top: 0px; right: 0px;">#</a></span><a aria-hidden="true" class="legacy" id="deprecations_dep0138_process_mainmodule" style="box-sizing: border-box;"></a></h4><div class="api_metadata" style="box-sizing: border-box; font-size: 0.85rem; margin-bottom: 1rem; color: rgb(255, 255, 255); font-family: Lato, &quot;Lucida Grande&quot;, &quot;Lucida Sans Unicode&quot;, &quot;Lucida Sans&quot;, Verdana, Tahoma, sans-serif; font-style: normal; font-variant-ligatures: none; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(9, 12, 21); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><details class="changelog" open="" style="box-sizing: border-box;"><summary style="box-sizing: border-box; margin: 0.5rem 0px; padding: 0.5rem 0px; cursor: pointer;">History</summary>

Version | Changes
-- | --
v14.0.0 | Documentation-only deprecation.

</details></div><p style="box-sizing: border-box; text-rendering: optimizelegibility; margin: 0px 0px 1.125rem; line-height: 1.5; color: rgb(255, 255, 255); font-family: Lato, &quot;Lucida Grande&quot;, &quot;Lucida Sans Unicode&quot;, &quot;Lucida Sans&quot;, Verdana, Tahoma, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: none; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(9, 12, 21); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Type: Documentation-only</p><p style="box-sizing: border-box; text-rendering: optimizelegibility; margin: 0px 0px 1.125rem; line-height: 1.5; color: rgb(255, 255, 255); font-family: Lato, &quot;Lucida Grande&quot;, &quot;Lucida Sans Unicode&quot;, &quot;Lucida Sans&quot;, Verdana, Tahoma, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: none; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(9, 12, 21); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><a href="https://nodejs.org/api/process.html#processmainmodule" style="box-sizing: border-box; color: var(--color-links); text-decoration: none; border-radius: 2px; padding: 1px 3px;"><code style="box-sizing: border-box; font-family: SFMono-Regular, Menlo, Consolas, &quot;Liberation Mono&quot;, &quot;Courier New&quot;, monospace; font-size: 0.9em; line-height: 1.5rem; margin: 0px; padding: 0px; color: var(--green3); background-color: var(--background-color-highlight); border-radius: 2px;">process.mainModule</code></a><span> </span>is a CommonJS-only feature while<span> </span><code style="box-sizing: border-box; font-family: SFMono-Regular, Menlo, Consolas, &quot;Liberation Mono&quot;, &quot;Courier New&quot;, monospace; font-size: 0.9em; line-height: 1.5rem; margin: 0px; padding: 1px 3px; color: var(--grey-smoke); background-color: var(--background-color-highlight); border-radius: 2px;">process</code><span> </span>global object is shared with non-CommonJS environment. Its use within ECMAScript modules is unsupported.</p><p style="box-sizing: border-box; text-rendering: optimizelegibility; margin: 0px 0px 1.125rem; line-height: 1.5; color: rgb(255, 255, 255); font-family: Lato, &quot;Lucida Grande&quot;, &quot;Lucida Sans Unicode&quot;, &quot;Lucida Sans&quot;, Verdana, Tahoma, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: none; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(9, 12, 21); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">It is deprecated in favor of<span> </span><a href="https://nodejs.org/api/modules.html#accessing-the-main-module" style="box-sizing: border-box; color: var(--color-links); text-decoration: none; border-radius: 2px; padding: 1px 3px;"><code style="box-sizing: border-box; font-family: SFMono-Regular, Menlo, Consolas, &quot;Liberation Mono&quot;, &quot;Courier New&quot;, monospace; font-size: 0.9em; line-height: 1.5rem; margin: 0px; padding: 0px; color: var(--green3); background-color: var(--background-color-highlight); border-radius: 2px;">require.main</code></a>, because it serves the same purpose and is only available on CommonJS environment.</p><br class="Apple-interchange-newline">DEP0138: process.mainModule[#](https://nodejs.org/api/deprecations.html#dep0138-processmainmodule)
History
Version	Changes
v14.0.0	
Documentation-only deprecation.

Type: Documentation-only

[process.mainModule](https://nodejs.org/api/process.html#processmainmodule) is a CommonJS-only feature while process global object is shared with non-CommonJS environment. Its use within ECMAScript modules is unsupported.

It is deprecated in favor of [require.main](https://nodejs.org/api/modules.html#accessing-the-main-module), because it serves the same purpose and is only available on CommonJS environment.

**Comment by vvscode** [comment]
@ljharb FYI^^

**Comment by ljharb** [comment]
I'm not going to use `require.main` ever, sorry. The current heuristic is my preferred approach.

**Comment by vvscode** [comment]
I proposed once, this mention was just to inform you about the state of that API. Thanks for helping me with the issues

Good luck
