### ISSUE TITLE
monorepo-symlink-test security issue

### ISSUE THREAD

**Issue by avosper-intellaegis** [browserify/resolve#319]
This package which is included in our project by a transitive dependency appears to include what the [`monorepo-symlink-test` package](https://github.com/browserify/resolve/blob/main/test/resolver/multirepo/package.json) which is identified as a malicious package in sca scanning tools such as AWS Inspector (9.8 - CRITICAL rating):

https://security.snyk.io/vuln/SNYK-JS-MONOREPOSYMLINKTEST-5865510

and has been set as  NPM Security Holding package: 

https://www.npmjs.com/package/monorepo-symlink-test

Other related bugs:

https://github.com/Unitech/pm2/issues/5669

**Comment by ljharb** [comment]
> Because it's a private package that just coincidentally has the same name as the malicious one, it is a false positive - so whatever tool is flagging this repo is broken, and you should strongly reconsider using a tool that is this naive about npm package names.

Duplicate of #303. Duplicate of #291. Duplicate of #288. Duplicate of #304. Duplicate of #305. Duplicate of #306. Duplicate of #309. Duplicate of #310. Duplicate of #311. Duplicate of #312. Duplicate of #314. Duplicate of #317. Duplicate of #318.
