### ISSUE TITLE
Any reason to publish /test? 

### ISSUE THREAD

**Issue by vvscode** [browserify/resolve#323]
I discovered (during some cleanup in my project repo) that `resolve` publishes `tests/` directory

and it's major part of the package https://www.npmjs.com/package/resolve?activeTab=code

![Screenshot 2023-11-23 at 15 56 56](https://github.com/browserify/resolve/assets/6904368/ef7f7c02-faa6-450c-aeb9-4d06097c572c)

is there any real need to publish it?

**Comment by vvscode** [comment]
I discovered it as I faced 

```
Error on: node_modules/eslint-plugin-react/node_modules/resolve/test/resolver/malformed_package_json/package.json
```

even though file marked as ignored at "package.json->publishConfig->ignore" https://github.com/browserify/resolve/blob/main/package.json#L80

and later I see that there is no such option `ignore` in the [doc](https://docs.npmjs.com/cli/v10/using-npm/config)

**Comment by vvscode** [comment]
ok, there is no such file in 1.22.8

but it's in `2.0.0-next.4` https://www.npmjs.com/package/resolve/v/2.0.0-next.4?activeTab=code

but I see you fixed it in `-next.5` correct?

**Comment by ljharb** [comment]
Yes, there’s a need and i do it in almost all of my packages. See #322 and many others.

**Comment by vvscode** [comment]
well, I do see that you do not provide any explanation, except your own will =))

anyway, it's your code, good luck

**Comment by ljharb** [comment]
I’ve provided much if you'd read the thread; here’s a tweet/video describing it better: https://twitter.com/matteocollina/status/1727651090340954410?s=46&t=se0vEhovmT79IfpN02iJcw
