### ISSUE TITLE
Provide canonical resolution resource for malicious code flag

### ISSUE THREAD

**Issue by duncanhall** [browserify/resolve#326]
Code that is included in this module when installed with a production flag is marked as malicious by many security tools.

While I disagree with the authors' stance of this, they have made clear their refusal to make amendments that could resolve this scenario within this package.

As an alternative, is there a single canonical resource or link that explains why this flag should be treated as a non-issue? There are at least a dozen closed issues around this, each with their own back-and-forth conversations. If we are left with no option but to treat this issue as 'ignored', it would really help if there were a discrete description of **why** everything is fine despite the security flag, such that it can be referenced or linked to by affected projects.

**Comment by ljharb** [comment]
No, it’s not - i renamed that package nearly a year ago - https://github.com/browserify/resolve/commit/c24f45137a441bc7bf6723b34f8db5ea5ddcacfa - so you clearly have no idea what you’re talking about.

**Comment by duncanhall** [comment]
Great to hear you renamed it! This kind of illustrates my point though - if you search for this issue, the results are a lot of back-and-forth arguments about why it isn't going to be changed. 

It's very possible I missed something obvious, but for those coming across this issue and searching for it, what is the thing you would hope they see to determine "aha, this is no longer an issue"?

**Comment by ljharb** [comment]
Yes, as should yours be - either you trust your scanner implicitly, and trust that it will stop you from a bad update, or you don’t, and you investigate and determine its validity for yourself.

All of the issues you referenced are closed, linking explicitly to that commit.
