### ISSUE TITLE
1.22.9 includes test/list-exports, reintroducing (false) malicious code flag

### ISSUE THREAD

**Issue by TomiTakussaari** [browserify/resolve#329]
Somehow, version 1.22.9 of resolve NPM package includes "/test/list-exports" directory, which contains, among other things, version 1.17.0 of this same library, in directory "test/list-exports/packages/tests/fixtures/resolve-1/".

This seems to reintroduce issue where different malicious code scanners identify this library as malicious, because one of those packages in that dir has name "monorepo-symlink-test".

Version 1.22.8 does not include this, and neither does 2.0.0-next.5. 
Git repository does not include those files either, so not sure where they came from.

Are those files there because something strange happened during NPM publish? Perhaps they are not really needed, and could be removed?

NPM package contents in 1.22.9:

<img width="1413" alt="Image" src="https://github.com/user-attachments/assets/526e802f-bfde-4348-aba9-6ecd884f13cb" />

NPM package contents in 1.22.8

<img width="1409" alt="Image" src="https://github.com/user-attachments/assets/f3945ff4-50bd-4b22-b999-3003f8e46a29" />

**Comment by ljharb** [comment]
Thanks, will fix shortly.

**Comment by TomiTakussaari** [comment]
Thanks, scanners are happy again :)
