### ISSUE TITLE
Tests fail to run on Windows

### ISSUE THREAD

**Issue by targos** [browserify/resolve#331]
See https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/3527/nodes=win-vs2022-arm64/testReport/junit/(root)/citgm/resolve_v1_22_10/

Should we skip this platform in CITGM? @ljharb

**Comment by ljharb** [comment]
If needed to reduce failures then ofc that's a good temporary fix.

However, it'd be ideal to fix the failure. What I see is
> lerna success Bootstrapped 2 packages
> npm error code ETARGET
> npm error notarget No matching version found for npm@'.

which is happening as part of `npm run test:multirepo`, but I definitely can't reproduce it on my Mac. I can try to repro it on Windows via Parallels though.

**Comment by targos** [comment]
https://github.com/browserify/resolve/pull/332
