### ISSUE TITLE
Expose more internal resolve logic

### ISSUE THREAD

**Issue by blakeembrey** [browserify/resolve#49]
A lot of the functions in both `lib/async.js` and `lib/sync.js` would be useful to reuse. I want to write a quick `resolve-glob` module (using this and glob), but right now that'll result in me copying/duplicating 90% of the logic that already exists here. Would you be open to a PR to correct this?

**Comment by iambumblehead** [comment]
Yes, it would be great if node-resolve could be used directly to compose other modules. Keeping the internal methods private makes it un-usable for this.

**Comment by iambumblehead** [comment]
I basically use [this][0] now and no longer need the resolve script here

[0]: https://github.com/iambumblehead/resolvewithplus

**Comment by ljharb** [comment]
@iambumblehead could you at least help me understand what that package offers that this one does not? making a fork doesn't help the wider community.

**Comment by iambumblehead** [comment]
@ljharb not responding to help queries for 4 years doesn't help the wider community.

At the time I needed to call that would take two paths --a filepath and a path, relative to the first path, that needed to be resolved according to the npm rules.

I tried to add such functionality here but, unfortunately, I found the code here to be unwieldy. Anyway, it was a long time ago.

**Comment by ljharb** [comment]
I'm going to close this, but am happy to reopen if use cases are provided.

**Comment by zxqfox** [comment]
It was so long time ago! Guess all is fine now
