### ISSUE TITLE
"Error: Cannot find module" output should include filename

### ISSUE THREAD

**Issue by jmm** [browserify/resolve#60]
When using browserify and there's a problem with the path to a module, I get error output like:

```
Error: Cannot find module 'module' from '/dir/subdir'
```

There may be any number of files in `subdir` that were trying to require the module. It would be really helpful for the error output to include the filename that contained the `require()` call instead of just the path to the dir it resides in.

**Comment by jmm** [comment]
This can be fixed if browser-resolve will pass through the original options it's called with. See defunctzombie/node-browser-resolve/pull/52. If you'd like to see this fixed please voice your support there.

**Comment by jmm** [comment]
@defunctzombie merged defunctzombie/node-browser-resolve/pull/52 to pass through the options, so I'll be working on a PR here for this.

**Comment by oliver----** [comment]
We would also love to see this fixed. What is the state of #64. Will it be merged eventually?

**Comment by jmm** [comment]
Made a plugin for this: https://www.npmjs.com/package/browserify-require-not-found-parent

**Comment by ljharb** [comment]
This will be taken care of once https://github.com/substack/node-resolve/pull/64#issuecomment-266689322 is rebased.

**Comment by A-312** [comment]
#162 is not merged on browsersify

Also 4 years after, this solution steals works fine: 

> Made a plugin for this: https://www.npmjs.com/package/browserify-require-not-found-parent

**Comment by ljharb** [comment]
@A-312 that PR is merged on this repo, and released in v1.8.0.
