### ISSUE TITLE
Support "browser" deep module references 

### ISSUE THREAD

**Issue by justinbmeyer** [browserify/resolve#62]
I would like to support re-pathing "deep" directory references with the browser config.  This was brought up [here](https://github.com/defunctzombie/node-browser-resolve/issues/51)  in node-browser-resolve. And it was [suggested here](https://github.com/defunctzombie/node-browser-resolve/issues/51#issuecomment-70414838) that the changes partly belong in node-resolve.

To make this change, I will need to change node-resolve to make a better attempt to find the package.json and `opts` hook that supports repathing.

`loadAsDirectory`, given a path like `x = "../node_modules/foo/bar"` will look for package.json in `"../node_modules/package.json"`.

If given a path without node_modules like: `x = "/Users/justin/dev/project/foo/bar"`, it will look for package.json in each folder until it finds it.

If a "deep" module reference is being resolved, a package.json is found, and an `opts.pathFilter` is found, `opts.pathFinder(pkg, x, relativeX)` will be called where:
- pkg - the package data 
- x - the moduleId attempted to be resolved
- relativeX - the moduleId path relative to the package.json location.

If `opts.pathFilter` returns a value, the returned value will be joined from the package.json location and passed to `loadAsFile`. Otherwise, x will be used with `loadAsFile`.

Example:

``` js
loadAsDirectory("/Users/justin/dev/project/foo/bar") 
  opts.pathFilter(pkg, "/Users/justin/dev/project/foo/bar", "./foo/bar") //-> "./browser/foo/bar"
  loadAsFile("/Users/justin/dev/project/browser/foo/bar", pkg)
```

Thoughts on this, the changes, and the choice of the `pathFilter` name and arguments?  Thanks!

/cc @defunctzombie

**Comment by justinbmeyer** [comment]
Actually, it seems that loadAsFile will need this behavior too.

**Comment by ljharb** [comment]
This seems addressed.
