### ISSUE TITLE
Possible loadAsFile inconsistencies

### ISSUE THREAD

**Issue by mattfysh** [browserify/resolve#66]
It seems that if resolving a path that matches the regexp
e.g. ./node_modules/jquery/jquery.min - then loadAsFile(String, Function) is called
however if the id takes format of "jquery/jquery.min", then loadAsFile(String, undefined, Function) is called

This results in opts.package being used only when the RegExp is matched. This has an upstream effect on browser-resolve and module-deps whereby if I use the first format, my transforms will apply inside of node_modules, but if I use the second, they don't... is this possibly a bug, or is there a reason behind it? Thanks!

**Comment by mattfysh** [comment]
@jaredhanson any thoughts on this one? I had a look at the changeset and it looks like it was a conscious choice to send undefined as 2nd param if id does not match regexp.

**Comment by ljharb** [comment]
I think this change was implemented [here](https://github.com/browserify/resolve/commit/60ff5545ec3cd15367c89c08cf3f139fa9c23796) - which links to https://github.com/defunctzombie/node-browser-resolve/issues/56.

I'm not sure what's specifically actionable here, so I'm going to close it, but I'm more than happy to reopen it if there's something specific we should be doing.
